"""Reusable profiling primitives that never mutate RAW source files."""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd


@dataclass(frozen=True)
class ProfileArtifacts:
    """Paths generated by one profiling execution."""

    summary: Path
    columns: Path
    missing_values: Path
    duplicate_keys: Path
    quality_issues: Path


def load_json_records(path: Path) -> list[dict[str, Any]]:
    """Load a JSON array while preserving the immutable input."""
    document = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(document, list) or not all(isinstance(item, dict) for item in document):
        raise ValueError("Expected a JSON array of objects")
    return document


def flatten_records(records: list[dict[str, Any]]) -> pd.DataFrame:
    """Flatten nested objects using stable dot-separated source paths."""
    return pd.json_normalize(records, sep=".")


def profile_columns(frame: pd.DataFrame) -> pd.DataFrame:
    """Calculate type, completeness, cardinality, and representative ranges."""
    rows: list[dict[str, Any]] = []
    total = len(frame)
    for column in frame.columns:
        series = frame[column]
        non_null = series.dropna()
        is_text = pd.api.types.is_string_dtype(series) or (
            not non_null.empty and isinstance(non_null.iloc[0], str)
        )
        rows.append(
            {
                "column": column,
                "dtype": str(series.dtype),
                "null_count": int(series.isna().sum()),
                "null_percentage": round(float(series.isna().mean() * 100), 6) if total else 0.0,
                "unique_count": int(series.nunique(dropna=True)),
                "cardinality_percentage": round(float(series.nunique(dropna=True) / total * 100), 6)
                if total
                else 0.0,
                "min": _safe_stat(non_null, "min"),
                "max": _safe_stat(non_null, "max"),
                "text_min_length": int(non_null.astype(str).str.len().min())
                if is_text and not non_null.empty
                else None,
                "text_max_length": int(non_null.astype(str).str.len().max())
                if is_text and not non_null.empty
                else None,
            }
        )
    return pd.DataFrame(rows)


def _safe_stat(series: pd.Series, operation: str) -> Any:
    if series.empty:
        return None
    try:
        value = getattr(series, operation)()
    except TypeError:
        return None
    return value.item() if hasattr(value, "item") else value


def municipality_quality_issues(frame: pd.DataFrame) -> pd.DataFrame:
    """Return records violating municipality-specific geographic rules."""
    issues: list[dict[str, Any]] = []
    required = {
        "id",
        "nome",
        "regiao-imediata.regiao-intermediaria.UF.sigla",
        "regiao-imediata.regiao-intermediaria.UF.regiao.nome",
    }
    missing_columns = required.difference(frame.columns)
    if missing_columns:
        raise ValueError(f"Missing required municipality columns: {sorted(missing_columns)}")

    valid_ufs = {
        "AC",
        "AL",
        "AP",
        "AM",
        "BA",
        "CE",
        "DF",
        "ES",
        "GO",
        "MA",
        "MT",
        "MS",
        "MG",
        "PA",
        "PB",
        "PR",
        "PE",
        "PI",
        "RJ",
        "RN",
        "RS",
        "RO",
        "RR",
        "SC",
        "SP",
        "SE",
        "TO",
    }
    valid_regions = {"Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"}
    for index, row in frame.iterrows():
        code = str(row["id"])
        checks = (
            (not code.isdigit() or len(code) != 7, "invalid_ibge_code"),
            (not str(row["nome"]).strip(), "missing_municipality_name"),
            (
                row["regiao-imediata.regiao-intermediaria.UF.sigla"] not in valid_ufs,
                "invalid_uf",
            ),
            (
                row["regiao-imediata.regiao-intermediaria.UF.regiao.nome"] not in valid_regions,
                "invalid_region",
            ),
        )
        for failed, reason in checks:
            if failed:
                issues.append({"row_index": index, "ibge_code": row["id"], "reason": reason})
    return pd.DataFrame(issues, columns=["row_index", "ibge_code", "reason"])


def write_municipality_profile(raw_path: Path, output_directory: Path) -> ProfileArtifacts:
    """Profile the official IBGE municipality directory and persist CSV/JSON evidence."""
    frame = flatten_records(load_json_records(raw_path))
    columns = profile_columns(frame)
    key_duplicates = frame.loc[frame.duplicated(subset=["id"], keep=False), ["id", "nome"]]
    full_duplicate_count = int(frame.duplicated(keep=False).sum())
    issues = municipality_quality_issues(frame)

    output_directory.mkdir(parents=True, exist_ok=True)
    artifacts = ProfileArtifacts(
        summary=output_directory / "municipality_profile_summary.json",
        columns=output_directory / "municipality_column_profile.csv",
        missing_values=output_directory / "missing_values_report.csv",
        duplicate_keys=output_directory / "municipality_duplicate_keys.csv",
        quality_issues=output_directory / "municipality_quality_issues.csv",
    )
    summary = {
        "source_file": str(raw_path),
        "shape": {"rows": len(frame), "columns": len(frame.columns)},
        "column_names": frame.columns.tolist(),
        "full_duplicate_rows": full_duplicate_count,
        "duplicate_ibge_codes": len(key_duplicates),
        "quality_issue_rows": len(issues),
        "ibge_code_min": int(frame["id"].min()),
        "ibge_code_max": int(frame["id"].max()),
        "municipality_name_min_length": int(frame["nome"].str.len().min()),
        "municipality_name_max_length": int(frame["nome"].str.len().max()),
        "municipalities_by_region": frame["regiao-imediata.regiao-intermediaria.UF.regiao.nome"]
        .value_counts()
        .sort_index()
        .to_dict(),
        "municipalities_by_uf": frame["regiao-imediata.regiao-intermediaria.UF.sigla"]
        .value_counts()
        .sort_index()
        .to_dict(),
    }
    artifacts.summary.write_text(
        json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    columns.to_csv(artifacts.columns, index=False)
    columns[["column", "null_count", "null_percentage"]].to_csv(
        artifacts.missing_values, index=False
    )
    key_duplicates.to_csv(artifacts.duplicate_keys, index=False)
    issues.to_csv(artifacts.quality_issues, index=False)
    return artifacts
