[server]
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0B6BCB"
backgroundColor = "#F4F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#243B53"
font = "sans serif"
